/* eslint-disable */
// This file is generated by the mop-plugin Vite plugin. Do not edit it manually.
import BackgroundModule from "./background.module.ts";
import CircleModule from "./circle.module.ts";

export type Modules = {
  BackgroundModule: BackgroundModule;
  CircleModule: CircleModule;
};
